const localNewsData = [
  {
    article_id: "09d5ff2d57d18a3add2130e39b5b973f",
    title:
      "Piramal Foundation Organizes Session and Rally on Violence Against Women and Menstrual Hygiene at New Sangbar",
    link: "https://www.sentinelassam.com/north-east-india-news/assam-news/piramal-foundation-organizes-session-and-rally-on-violence-against-women-and-menstrual-hygiene-at-new-sangbar",
    keywords: null,
    creator: ["Sentinel Digital Desk"],
    video_url: null,
    description: null,
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-12-07 05:01:47",
    pubDateTZ: "UTC",
    image_url:
      "https://media.assettype.com/sentinelassam-english%2F2024-12-07%2Ffgp816mf%2Fpiramal.jpg?auto=format%2Ccompress&fit=max&w=480",
    source_id: "sentinel",
    source_priority: 177615,
    source_name: "The Sentinel",
    source_url: "https://www.sentinelassam.com",
    source_icon: "https://i.bytvi.com/domain_icons/sentinel.jpg",
    language: "english",
    country: ["india"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "de92f0888cd5ef02eed1fede126a4542",
    title:
      "KSEB power tariff hike: Household bills to rise by Rs 14 to Rs 300 based on usage",
    link: "https://english.mathrubhumi.com/news/kerala/revised-electricity-rates-came-into-effect-from-thursday-in-kerala-1.10143073",
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "Thiruvananthapuram: Electricity rates in the state have been increased by an average of 16 paise. The revised rates came into effect from Thursday. For ...",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-12-07 05:01:44",
    pubDateTZ: "UTC",
    image_url:
      "https://english.mathrubhumi.com/image/contentid/policy:1.9094016:1733547757/KSEB%20(2).jpg?%24p=d1509d1&f=16x10&q=0.8&w=852",
    source_id: "mathrubhumi",
    source_priority: 29098,
    source_name: "Mathrubhumi English",
    source_url: "https://english.mathrubhumi.com",
    source_icon: "https://i.bytvi.com/domain_icons/mathrubhumi.png",
    language: "english",
    country: ["india"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "7b308c533e2ea1aefb3f2c866b6be059",
    title:
      "Indian Army Honors Cadet Jodha Thongjaomayum for President's Bronze Medal at NDA Passing Out Parade",
    link: "https://www.freepressjournal.in/pune/indian-army-honors-cadet-jodha-thongjaomayum-for-presidents-bronze-medal-at-nda-passing-out-parade",
    keywords: ["pune news"],
    creator: null,
    video_url: null,
    description: null,
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-12-07 05:01:24",
    pubDateTZ: "UTC",
    image_url:
      "https://media.assettype.com/freepressjournal/2024-12-07/1urcmxfm/GeFxVHXXYAAh8g7.jpg",
    source_id: "freepressjournal",
    source_priority: 83130,
    source_name: "The Free Press Journal",
    source_url: "https://www.freepressjournal.in",
    source_icon: "https://i.bytvi.com/domain_icons/freepressjournal.png",
    language: "english",
    country: ["india"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "284c7fb22823cf097d09279cebc50e11",
    title:
      "Elon Musk, world’s richest man, spent over Rs 22000000000 to help Donald Trump win second term as US President",
    link: "https://www.india.com/news/world/elon-musk-worlds-richest-man-spent-over-rs-22000000000-to-help-donald-trump-win-second-term-as-us-president-with-usd-270-million-7447787/",
    keywords: ["donald trump", "world", "elon musk"],
    creator: null,
    video_url: null,
    description:
      "Elon Musk's contributions, which earned him an advisory role in Trump’s upcoming administration, are the largest political donation by any individual since at least 2010, based on data from the nonprofit OpenSecrets.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-12-07 05:01:13",
    pubDateTZ: "UTC",
    image_url:
      "https://static.india.com/wp-content/themes/icom/images/default-big.svg",
    source_id: "india",
    source_priority: 8067,
    source_name: "India",
    source_url: "https://www.india.com",
    source_icon: "https://i.bytvi.com/domain_icons/india.png",
    language: "english",
    country: ["india"],
    category: ["world"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "d9bcceb8e9101534e0eb0977c3091839",
    title:
      "Karan Aujla Chandigarh concert: Traffic advisory issued, security heightened | know your parking spot",
    link: "https://www.ptcnews.tv/top-stories/karan-aujla-chandigarh-concert-traffic-advisory-issued-security-heightened-4402800",
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "PTC News Desk: Punjabi singer Karan Aujla is all set to rock with his concert in Chandigarh today. In wake of the concert, Chandigarh traffic police has issued traffic advisory for the day and several",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-12-07 05:01:10",
    pubDateTZ: "UTC",
    image_url:
      "https://media.ptcnews.tv/wp-content/uploads/2024/08/c1d409e546ac08e2bdc011acf4b7e204_1280X720.webp",
    source_id: "ptcnews",
    source_priority: 211063,
    source_name: "Ptc News",
    source_url: "https://www.ptcnews.tv",
    source_icon: "https://i.bytvi.com/domain_icons/ptcnews.jpg",
    language: "english",
    country: ["india"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
];

export default localNewsData;
